spring.application.name=TimeManagerApplication

spring.datasource.url=jdbc:mysql://localhost:3306/time_manager_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

# JWT Configuration
app.jwtSecret=TimeManagerSuperSecretKeyForJwtGenerationDoNotShareThisKeyWithAnyone1234567890!@#$
app.jwtExpirationMs=86400000 
# 86400000 ms = 1 ngay (Access Token song 1 ngay)

# Cau hinh Email Server (Dung Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=22t1020628@husc.edu.vn
spring.mail.password=rugw dqjo ubzu mspx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.open-in-view=false  

# Kich hoat tinh nang lap lich (Scheduling)
spring.task.scheduling.pool.size=2
